# Generated by Django 5.1.7 on 2025-03-19 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('weight', 'Weight'), ('calories', 'Calories'), ('activity', 'Activity'), ('hr', 'Heart Rate'), ('sleep', 'Sleep'), ('other', 'Other')], default='other', max_length=20)),
                ('target_value', models.FloatField(help_text='Target value (e.g., target weight in lbs, activity minutes, etc.)')),
                ('current_value', models.FloatField(default=0, help_text='Current progress value')),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
