# Generated by Django 5.1.7 on 2025-03-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.AddField(
            model_name='goal',
            name='comparison',
            field=models.CharField(choices=[('min', 'Minimize'), ('max', 'Maximize')], default='min', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('weight', 'Weight'), ('calories', 'Caloric Intake'), ('activity', 'Physical Activity'), ('sleep', 'Sleep')], default='weight', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(help_text='Target value (in appropriate units, e.g. lbs for weight, calories, minutes, or hours)'),
        ),
    ]
