# Generated by Django 5.1.7 on 2025-03-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_time', models.TimeField(help_text='Scheduled time for this dose')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='medications.medication')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='medicationlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='dose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.medicationdose'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationlog',
            unique_together={('medication', 'dose', 'date')},
        ),
    ]
