# Generated by Django 5.1.7 on 2025-03-19 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medicationdose_alter_medicationlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dosing_schedule',
            field=models.CharField(blank=True, help_text="General instructions (e.g., 'Take with food')", max_length=100),
        ),
        migrations.CreateModel(
            name='MedicationDoseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField(help_text='Time of day when the dose should be taken.')),
                ('recurring_days', models.CharField(blank=True, help_text="Comma-separated weekdays (e.g., 'Mon,Wed,Fri'). Leave blank for every day.", max_length=50)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_times', to='medications.medication')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='medicationlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='dose_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.medicationdosetime'),
        ),
        migrations.AlterUniqueTogether(
            name='medicationlog',
            unique_together={('medication', 'date', 'dose_time')},
        ),
        migrations.RemoveField(
            model_name='medicationlog',
            name='dose',
        ),
        migrations.DeleteModel(
            name='MedicationDose',
        ),
    ]
