"""
Django settings for the Healthy You project.

This file contains settings and configuration for the project.
Generated by 'django-admin startproject'.

For more details, visit:
https://docs.djangoproject.com/en/stable/topics/settings/

For the full list of settings, see:
https://docs.djangoproject.com/en/stable/ref/settings/
"""

from pathlib import Path

# Base directory path for the project
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------------------------
# Security settings
# ----------------------------------------------------------------------

# WARNING: Keep the secret key secret in production! Do not hardcode it.
SECRET_KEY = 'django-insecure-7!y1=iov+8%5%mx!v*ol#cjmk=r+-c(v@f6aqc1&p*7cz1awre'

# Do not run with debug enabled in production environments.
DEBUG = True

# Defines allowed hosts when deploying the application.
ALLOWED_HOSTS = []

# ----------------------------------------------------------------------
# Application definition
# ----------------------------------------------------------------------

INSTALLED_APPS = [
    # Core Django applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party applications
    'rest_framework',  # Django REST Framework for APIs
    'crispy_forms',  # Better form rendering
    'crispy_bootstrap4',  # Bootstrap 4 templates for crispy forms

    # Custom or modular applications
    'accounts',
    'health',
    'medications',
    'sleep',
    'goals',
    'appointments',
    'reports',
]

# Specify the template pack for crispy-forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root URL configuration module
ROOT_URLCONF = 'healthy_you.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Path to custom template directory
        'APP_DIRS': True,  # Automatically locate templates inside app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application entry point
WSGI_APPLICATION = 'healthy_you.wsgi.application'

# ----------------------------------------------------------------------
# Database configuration
# ----------------------------------------------------------------------

# Default database: SQLite (for development purposes)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ----------------------------------------------------------------------
# Password validation
# ----------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ----------------------------------------------------------------------
# Internationalization
# ----------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'  # Language code for the application
TIME_ZONE = 'UTC'  # Default timezone
USE_I18N = True  # Enable internationalization
USE_TZ = True  # Enable timezone support

# ----------------------------------------------------------------------
# Static files
# ----------------------------------------------------------------------

STATIC_URL = 'static/'  # URL path for serving static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Custom static files directory
]

# ----------------------------------------------------------------------
# Default primary key field type
# ----------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------------------------------------
# Celery (Task Queue) Configuration
# ----------------------------------------------------------------------

# Use Redis as the Celery message broker
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# ----------------------------------------------------------------------
# Email Backend Configuration
# ----------------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Email debugging
DEFAULT_FROM_EMAIL = 'noreply@healthyyou.com'  # Default "from" email address
